### ISSUE TITLE
Clang-format newlines at EOF

### ISSUE THREAD

**Issue by Shillaker** [faasm/faasm#318]
Enforce a consistent style on this (either with or without, but it should be impossible to pass the check if the file has the wrong ending).

Note that the check that we perform in CI will be with [`run_clang_format.sh`](https://github.com/faasm/faasm/blob/master/bin/run_clang_format.sh).

**Comment by csegarragonz** [comment]
**Identifying the problem:**

Disclaimer: I might have overengineered this a bit, but whatever. 

I have written the following test script `newline_test.sh`:
```bash
#!/bin/bash
# Based on (some tweaks by me):
# https://stackoverflow.com/questions/34943632/linux-check-if-there-is-an-empty-line-at-the-end-of-a-file
# As a reminder:
# -f tests if the file is a regular file (i.e. not directory or device file)
# -s tests if the file is not 0 bytes
# -z tests if the string is null
# -c in tail outputs the last byte
# Usage:
# ./newline_test.sh $(find <root_dir> -name "*.c" -o -name "*.cpp" -o -name "*.h")
for f in "$@"
do
    if [[ -f "$f" && -s "$f" ]];
    then
        if [[ -z "$(tail -c 1 "$f")" ]];
        then
            :
        else
            echo "No newline at: $f"
        fi
    fi
done
```

It is useful to tell which files have a trailing newline and which not. It's clear that there's divergence as running it on `faasm/src` outputs the following:
```bash
No newline at: ./src/storage/SharedFiles.cpp
No newline at: ./src/storage/FileSystem.cpp
No newline at: ./src/storage/FileserverFileLoader.cpp
No newline at: ./src/wavm/dynlink.cpp
No newline at: ./src/wavm/network.cpp
No newline at: ./src/wavm/process.cpp
No newline at: ./src/wavm/messages.cpp
No newline at: ./src/wavm/timing.cpp
No newline at: ./src/wavm/faasm.cpp
No newline at: ./src/wavm/util.cpp
No newline at: ./src/wavm/syscalls.cpp
No newline at: ./src/wavm/typescript.cpp
No newline at: ./src/wavm/signals.cpp
No newline at: ./src/wavm/memory.cpp
No newline at: ./src/wavm/syscalls.h
No newline at: ./src/faaslet/Faaslet.cpp
No newline at: ./src/emulator/emulator.cpp
No newline at: ./src/runner/func_sym.cpp
No newline at: ./src/runner/codegen_func.cpp
No newline at: ./src/runner/func_runner.cpp
No newline at: ./src/sgx/sgx_runner.cpp
No newline at: ./src/sgx/demo_keymgr.c
No newline at: ./src/sgx/sgx_wamr_enclave.cpp
No newline at: ./src/sgx/sgx_wamr_native_symbols.cpp
No newline at: ./src/sgx/sgx_wamr_whitelisting.cpp
No newline at: ./src/sgx/rw_lock.cpp
No newline at: ./src/sgx/sgx_system.cpp
No newline at: ./src/sgx/sgx_wamr_attestation.cpp
No newline at: ./src/wamr/WAMRWasmModule.cpp
No newline at: ./src/wamr/native.cpp
No newline at: ./src/module_cache/WasmModuleCache.cpp
No newline at: ./src/wasm/chaining_util.cpp
No newline at: ./src/wasm/WasmEnvironment.cpp
No newline at: ./src/upload/upload_server.cpp
```
Note that, an alternative manual check is running `cat -e <file_name>`. If the last character outputed is a `%` then the file has no trailing newline. Otherwise, if the last character is a `$`, that means there is a trailing newline. For instance, test the following in `src/wavm/process.cpp` vs `src/wavm/rust.cpp`.

**The problem:**

As a consequence, it seems clear that the `clang-format` does not enforce one neither the other. Yet this is not exactly true. If I run `./bin/run_clang_format.sh src/wavm` I get an empty string (i.e. checks pass). Yet, if I go to a specific file i.e. `./src/wavm/messages.cpp` and I run the format _locally_ within `vim`, `clang-format` adds an extra newline.

There's way more drama than expected [1](https://jira.mongodb.org/browse/SERVER-35466), [2](https://reviews.llvm.org/D70864), [3](https://github.com/google/vim-codefmt/issues/83), and the list goes on...

**Picking a side:**

It [seems](https://stackoverflow.com/questions/31574837/c-standards-newline-ending-of-source-files) that the C++ standard enforces including a newline at the end of a file (I have seen several SO posts mentioning it, but I am too lazy to look for the actual entry in the reference, although the post I link seems pretty l3git).

**Solution:**

I have _not_ (90' in) found a reason on why this might be happening. I have a workaround, but it's quite dirty. Using the script presented above, we can easily add a trailing newline to those files who don't have it, the resulting script is the following one (note the extra line added):
```bash
#!/bin/bash
# Based on (some tweaks by me):
# https://stackoverflow.com/questions/34943632/linux-check-if-there-is-an-empty-line-at-the-end-of-a-file
# As a reminder:
# -f tests if the file is a regular file (i.e. not directory or device file)
# -s tests if the file is not 0 bytes
# -z tests if the string is null
# -c in tail outputs the last byte
# Usage:
# ./newline_test.sh $(find <root_dir> -name "*.c" -o -name "*.cpp" -o -name "*.h")
for f in "$@"
do
    if [[ -f "$f" && -s "$f" ]];
    then
        if [[ -z "$(tail -c 1 "$f")" ]];
        then
            :
        else
            echo "No newline at: $f"
            echo >>"$f"
        fi
    fi
done
```

I haven't been able to come up with a better solution. On the bright side, once all files have a trailing newline - and given that Git keeps track of it - we'll be able to tell if someone else editing has _removed_ said newline. Additionally, we could include the latter script in the format check, as there's no way to define _custom_ formatting rules in `clang-format`.

**Comment by Shillaker** [comment]
:joy: oh wow, what a can of worms... classic bikeshedding :smile: 

I think the final script looks great though, so shall we merge it into `run_clang_format.sh`? Something like (untested):

```bash
#!/bin/bash

set -e

function append_newline {
    if [[ -z "$(tail -c 1 "$1")" ]]; then
        :
    else
        echo >> "$1"
    fi
}

if [ -z "$1" ]; then
    TARGET_DIR="."
else
    TARGET_DIR=$1
fi

pushd ${TARGET_DIR} >> /dev/null

# Find all source files using Git to automatically respect .gitignore
FILES=$(git ls-files "*.h" "*.cpp" "*.c")

# Run clang-format
clang-format-10 -i ${FILES}

# Check newlines
for f in ${FILES}; do
    append_newline $f
done

popd >> /dev/null
```

There is also the matter of enforcing a _single_ newline at the end of the file, rather than many, but we can leave that for another day...
