### ISSUE TITLE
Completely remove SGX from normal build and test

### ISSUE THREAD

**Issue by Shillaker** [faasm/faasm#617]
Now that we will have separate SGX containers, we can remove SGX from the default container, and have two test runs in GHA:

* Normal build and tests: runs the build in the default containers with `FAASM_SGX_MODE=Disabled`, and does all the normal sanitiser stuff
* SGX build and tests: runs the build in the SGX containers with `FAASM_SGX_MODE=Simulation`, then execute all the tests including the SGX ones (but none of the sanitiser stuff).

This is better than the situation we have now, as at the moment we don't check the build on a system without SGX installed (and this is the default expected setup for users).

**Comment by csegarragonz** [comment]
At the moment, we only use a different container tag to build SGX in hardware mode (`base-sgx` and `worker-sgx`). The reason is that the linking and compilation must be different between simulation and hardware builds. If we were to support a build with SGX disabled, we'd need yet a third container for sgx in simulation mode.

Other than the sanitiser stuff (I could give a crack at running sanitisers on SGX, I have seen a couple of related PRs) what is the problem with our current set up in `Simulation` mode?

> This is better than the situation we have now, as at the moment we don't check the build on a system without SGX installed (and this is the default expected setup for users).

AFAICT the expected setup for users is through the containerised build, and in that case they are guaranteed to have the SGX SDK (sufficient to run in `Simulation` mode). What is not expected IMO is that they have an SGX-capable CPU, that's why `Hardware` builds are a whole different thing, and why we have a script to check the user's setup.

**Comment by Shillaker** [comment]
To do this, we'd need:

- Remove all SGX-related setup and SGX container inheritance from standard Docker images, compile Faasm with SGX disabled.
- Convert existing `sgx` image into a new `base-sgx` image, which extends `base`, and includes the setup from `base`[https://github.com/faasm/faasm/blob/main/docker/base.dockerfile].
- Add new Docker image builds so that we have: `worker`, `worker-sgx-hw` (extends `base-sgx` and compiled with hardware mode), `worker-sgx-sim` (extends `base-sgx` and compiled with simulation mode), and equivalent for `upload`.
- Add new Docker image build for `cli-sgx-sim`, which is the CLI image inheriting from `base-sgx` rather than `base`, with the code compiled with SGX simulation support.
- Add separate GHA step to run SGX tests in the `cli-sgx-sim` container.
- Update release build to run all these Docker image builds in parallel.
