### ISSUE TITLE
`./bin/cli.sh faasm` not working from zsh

### ISSUE THREAD

**Issue by mmathys** [faasm/faasm#669]
Running `./bin/cli.sh faasm` from `zsh` returns the error

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "/usr/bin/zsh": stat /usr/bin/zsh: no such file or directory: unknown
```

Setting this environment variable helps:

```bash
export SHELL=bash
```

This could be added to the `cli.sh` script.

**Comment by csegarragonz** [comment]
This happens because we allow developers to overwrite the `FAASM_CLI_IMAGE` with a custom image with ad-hoc dependencies installed (e.g. `zsh` instead of `bash` as shell).

We assume (maybe not a correct assumption?) that you will want to use the same shell in Faasm's development environment than in your shell environment. In general, when developing Faasm you will start the client setting a couple of env. variables, like:

```bash
FAASM_CLI_IMAGE=my/custom_cli_image SHELL=fish ./bin/cli.sh faasm
```

Originally, the `SHELL` thing was not a big deal as all the environments we developed in (and all the developers) used `bash`.
