### ISSUE TITLE
Creating new users and uploading files

### ISSUE THREAD

**Issue by JefferyLim** [faasm/faasm#796]
I have a questions pertaining to the issue:

My understanding of doing development is that there are multiple options:
     1. You can enter the cpp or the python container, write code, compile, and then upload it to be invoked
     2. You can upload WASM files to be invoked later on.

My question is are there any other way of developing functions? Is it entirely reliant on using the cpp or python containers to compile and upload the functions and test?

The second question becomes the user parameter when used in the func.upload/func.invoke. How does one go about creating a new user? Is it just the directory? Is it reliant on the structure in cpp/func/? It's not clear to me how I go about making a "jeff" user for my own functions to be created and uploaded.

**Comment by csegarragonz** [comment]
The `user, func` pair is a way in Faasm to identify functions. There are two places in which these pairs are used.

First, when `upload`-ing a function to Faasm you indicate, in general, a `user, func` pair and a WASM file. After that, this WASM file can be invoked using the `user,func` pair.

As you said, this WASM file could, in theory, come from anywhere. However, this is not true in practice. Faasm is not (and doesn't aim to be) a general purpose Faasm runtime. We have our custom host interface and compile WASM with our custom compilation flags, for our supported runtimes. As a consequence, when cross-compiling (e.g.) C/C++ to WASM for Faasm, you need to use a special compilation toolchain.

The CPP and Python containers aim to make this simpler, by packaging the compilation toolchains in a way that it is easy to consume. This simplicity comes at the expense of less generality, we have [`CMake` files](https://github.com/faasm/cpp/blob/main/func/CMakeLists.txt#L72-L76) hard-coding "users" in the C++ container.

There are two ways you could go about easily compiling and uploading functions for user `jeff`:
1. If the functions are simple enough, you could tweak the linked CMake files in the CPP container so that you can run `inv func jeff hello`.
2. The more general approach, would be to build your own toolchain container, and compile arbitrary WASM files, and then upload them manually under the `jeff` user. This is what we do in the [examples](https://github.com/faasm/examples/blob/main/docker/build.dockerfile) repo.

**Comment by csegarragonz** [comment]
Will close this issue, please feel free to re-open or open another one if the error persists.
