### ISSUE TITLE
How to measure performance?

### ISSUE THREAD

**Issue by kaimast** [faasm/faasm#797]
I am trying to measure the performance of Faasm and have two questions.

**Latency**
How do I measure the end-to-end latency? There does not seem to be a way to send synchronous requests. The invoke mechanism in `faasmctl` seems to only support batching and will poll every 2 seconds.
That means the minimum end-to-end latency that can be observed is two seconds. That's really high considering Wasm runtimes can execute functions in less than a millisecond.

**Throughput**
Workers do not automatically spawn additional containers (correct me if I am wrong), so the number of workers is the maximum number of concurrent requests.
What is a good number of workers to set then? For non-blocking functions, it seems like the number of CPUs is sufficient, but for functions that block on requests (e.g., waiting for the database to respond) a higher number of workers might be needed.
But I am not sure if there is some upper limit of workers or some point where additional workers harm performance.

Thanks for your help!

**Comment by csegarragonz** [comment]
Hi! 

The project is slowly evolving towards running longer-running distributed applications (rather than being purely a serverless runtime), so you will have to take some of the measurements with a grain of salt. That being said, it should still be possible to measure both latency and throughput.

In terms of latency, as you said, we only support asynchronous requests now. This is because all results are stored in the `planner`, a newly-introduced centralized component (very non-serverless btw), so synchronous requests could easily overwhelm the HTTP server. That being said, you could easily change that without affecting the underlying worker functionality at all. Even without changing anything, there's a way to get the exact time a function spent executing by inspecting the result message. See how it is done [here](https://github.com/faasm/experiment-mpi/blob/main/tasks/lammps/run.py#L91C1-L92).

In terms of throughput, we always have one worker per container per VM (we force this with an anti-affinity policy in Kubernetes). The fact that we can run arbitrarily many workers in a `docker compose` cluster is just for testing and development purposes. That being said, the maximum number of concurrent requests is the product between the number of workers and the perceived number of CPU cores from each worker (i.e. [`faabric::util::getUsableCores()`](https://github.com/faasm/faabric/blob/main/src/util/environment.cpp#L38-L55)). This number can be easily fooled by overwriting an envrionment variable (see how we do it for [`docker compsoe`](https://github.com/faasm/faasm/blob/main/docker-compose.yml#L99)). Faaslets, Faasm isolation units, are similar to threads, so if needed (and most of your workloads are blocking on IO) you should be able to jack that number up.

Hope this helps!

**Comment by kaimast** [comment]
Thanks for the detailed reply!

Maybe I am doing something wrong, but I can only process one request per worker. My system has more than 1 CPU core though. 
I will look into overwriting the environment variable...

Going through the planner is indeed kind of slow. It also seems to be bottlenecked on a single thread. 
Do you think it's feasible to issue requests to the workers directly? Meaning I would write a custom client that talks whatever protocol the planner uses to talk to the workers.

**Comment by kaimast** [comment]
I spawn a number of clients and they issue their requests to the planner and then periodically poll for their completion, like it is done in faasmctl. 

When there are, for example, three clients and two workers I get the following response from the planner: `No available hosts`

With bottlenecked I mean the planner never goes beyond 100% CPU while the workers barely use any CPU cycles. Looking at [the code](https://github.com/faasm/faabric/blob/e98e917702cf43453d8500a96740255c87677b45/src/planner/Planner.cpp#L469C45-L469C45) it seems to me that only a single batch can be scheduled at a time, but I could be wrong.
